#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_statusline_mode = false
    
    ########################################
    #             USER OPTIONS             #
    ########################################
    default_indent = 4
    # accesses ~/.SpaceVim.d/autoload/my_config.vim
    bootstrap_before = "my_config#before"
    bootstrap_after = "my_config#after"
    #
    disabled_plugins = []
    # reclaim q for recording
    windows_smartclose = ""
    # colorscheme
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # customize status line
    statusline_separator = "slant"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    statusline_left_sections = [
        'winnr',
        'filename',
        'major mode',
        'minor mode lighters',
        'version control info'
        ]
    statusline_right_sections = [
        # 'fileformat',
        'cursorpos',
        'percentage'
        ]
    # get my leader key back
    enable_language_specific_leader = false


# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "smart"
    auto_completion_tab_key_behavior = "cycle"
    auto_completion_enable_snippets_in_popup= true

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "lang#python"
    python_file_head = [
        '#!/usr/local/bin python3',
        '# -*- coding: utf-8 -*-',
        '',
        ''
    ]

[[layers]]
    name = "colorscheme"

